id: IF1422D74
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:07:09+00:00'
last_modified: '2022-06-15T18:46:01.720827+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21588
  title: གསོ་རིག་གཅེས་བཏུས་རིན་ཆེན་ཕྲེང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4A5F:
      image_group_id: I4198
      title: ''
      total_pages: 786
      order: 1
      base_file: 4A5F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
